apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"deployapp","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"deployapp"}},"template":{"metadata":{"labels":{"app":"deployapp"},"name":"podapp"},"spec":{"containers":[{"image":"nginx","name":"node","ports":[{"containerPort":8085}],"resources":{"limits":{"cpu":"150m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2021-11-03T06:31:27Z"
  generation: 13
  name: deployapp
  namespace: default
  resourceVersion: "10642834"
  uid: c1b45444-fbbb-42bb-bdca-97bbff758e2d
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployapp
      name: podapp
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: node
        ports:
        - containerPort: 8085
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-11-03T06:31:27Z"
    lastUpdateTime: "2021-11-03T06:31:38Z"
    message: ReplicaSet "deployapp-bf765d846" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-03T06:37:25Z"
    lastUpdateTime: "2021-11-03T06:37:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
