# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --disable-partition-engine-check
    # restart: always
    environment:
      MYSQL_DATABASE: memid
      MYSQL_ROOT_PASSWORD: 8888
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
      # - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - common

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - common

volumes:
  data:
networks:
  common:
    driver: bridge
